version: '3'
services:
  node_application:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo_database
  mongo_database:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
